### ISSUE TITLE
Question about RequestContext

### ISSUE THREAD

**Issue by DASPRiD** [mikro-orm/koa-ts-example-app#1]
After looking through the `RequestContext` code as well as reading about `asyncLocalStorage`, I came to wonder. In the following line, the controller accesses the exported original instance of the EM, if I understood it correctly:

https://github.com/mikro-orm/koa-ts-example-app/blob/d4cccc833c4edb2daed5941decf4fbd7e792a8ce/app/controllers/author.controller.ts#L11

Based on the source of `RequestContext`, shouldn't this be something like this?

```typescript
RequestContext.getEntityManager().find(/* … */);
```

If yes, this seems to be sub-optimal, as `getEntityManager()` can return undefined. Maybe there should be a safer variant which throws an exception when not within the request context.

**Comment by B4nan** [comment]
Nope, that is done automatically, and in v5 you get an error if you use global em without accessible context.
