### ISSUE TITLE
TS issues while following the instructions

### ISSUE THREAD

**Issue by christopher-caldwell** [mikro-orm/koa-ts-example-app#16]
Hi there, I am getting some TS errors when following the instructions for this.

Looks like the findAll signature is different? It expects a single object.
<img width="977" alt="Screen Shot 2023-06-28 at 7 16 48 PM" src="https://github.com/mikro-orm/koa-ts-example-app/assets/62559469/155a1351-3709-4714-8ce9-44944135f22e">

Here are the errors I am seeing when running `yarn start`
<img width="1486" alt="Screen Shot 2023-06-28 at 7 16 58 PM" src="https://github.com/mikro-orm/koa-ts-example-app/assets/62559469/631866c2-5b1b-4c03-a364-31355a3329a3">

**Comment by B4nan** [comment]
The code is outdated and based on v4 (but received v5 update via renovate bot mistakenly).

Check the v5 upgrading guide here:

https://mikro-orm.io/docs/upgrading-v4-to-v5

**Comment by christopher-caldwell** [comment]
Is it worth updating the example? I can try to put it together.

**Comment by B4nan** [comment]
Yeah definitely, PR welcome.
